#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SUCCESS 1
#define FAIL 0
#define INITIAL_LENGTH 10
#define PRINT_LENGTH 30
#define INITIAL_DOMAIN_SIZE 3
#define ASSUMED_DISTANCE 0.3 /* 3Å */
#define ASSUMED_ANGLE 20 /* in degrees */
#define PI 3.141592653589793 
#define INITIAL_EDGE_NUMBER 2
#define INITIAL_HEAP_SIZE 3
#define PDB_LINE_LENGTH_BUFFER 100 /* a little extra */
#define HYDROGEN_IDENTIFIER 2
#define NON_HYDROGEN_IDENTIFIER 1

#endif
